import { useState } from "react";
import { Card } from "./Card";
import type {
  PeriodKind,
  Summary,
  SummaryVariant,
} from "@/types/summary";
import type { Range } from "@/lib/time";
import type { Goal } from "@/types/goal";
import { useActivity } from "@/stores/activityStore";
import { useSettings } from "@/stores/settingsStore";
import { Copy, Wand2 } from "lucide-react";

const VARIANTS: Array<{ id: SummaryVariant; label: string; sub: string }> = [
  { id: "standard", label: "Daily recap", sub: "What you worked on" },
  { id: "boss", label: "Boss-ready update", sub: "Share upward" },
  { id: "executive", label: "Executive summary", sub: "One-paragraph outcomes" },
  { id: "self_review", label: "Self-review bullets", sub: "For performance reviews" },
];

export function SummaryPanel({
  period,
  range,
  goals,
}: {
  period: PeriodKind;
  range: Range;
  goals: Goal[];
}) {
  const { settings } = useSettings();
  const { summaries, buildSummary } = useActivity();
  const [variant, setVariant] = useState<SummaryVariant>("standard");
  const [generating, setGenerating] = useState(false);

  const current = summaries.find(
    (s) =>
      s.period_kind === period &&
      s.period_start === range.start &&
      s.variant === variant
  );

  const onGenerate = async () => {
    setGenerating(true);
    try {
      await buildSummary({
        range,
        periodKind: period,
        variant,
        goals,
        settings,
      });
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Card
      title="Summary"
      subtitle={`${period === "day" ? "Today" : period === "week" ? "This week" : "This month"} · ${VARIANTS.find((v) => v.id === variant)?.sub}`}
      action={
        <button
          onClick={onGenerate}
          disabled={generating}
          className="inline-flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-md bg-brand-600 text-white hover:bg-brand-700 disabled:opacity-50"
        >
          <Wand2 className="w-4 h-4" />
          {current ? "Regenerate" : "Generate"}
        </button>
      }
    >
      <div className="flex gap-2 mb-4 flex-wrap">
        {VARIANTS.map((v) => (
          <button
            key={v.id}
            onClick={() => setVariant(v.id)}
            className={
              "text-xs px-3 py-1.5 rounded-md border " +
              (variant === v.id
                ? "bg-brand-50 border-brand-200 text-brand-700"
                : "bg-white border-ink-200 text-ink-600 hover:bg-ink-50")
            }
          >
            {v.label}
          </button>
        ))}
      </div>

      {current ? (
        <SummaryBody s={current} />
      ) : (
        <p className="text-sm text-ink-500">
          No summary yet for this view. Click <b>Generate</b> above.
        </p>
      )}
    </Card>
  );
}

function SummaryBody({ s }: { s: Summary }) {
  return (
    <div>
      <pre className="whitespace-pre-wrap font-sans text-sm text-ink-700 leading-6 bg-ink-50 border border-ink-100 rounded-md p-4">
        {s.text}
      </pre>
      <div className="mt-2 flex justify-between items-center text-xs text-ink-400">
        <span>Generated by {s.model}</span>
        <button
          onClick={() => navigator.clipboard.writeText(s.text)}
          className="inline-flex items-center gap-1 hover:text-ink-700"
        >
          <Copy className="w-3.5 h-3.5" /> Copy
        </button>
      </div>
    </div>
  );
}
